name: maven-release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          settings-path: ${{ github.workspace }}

      - name: Publish with Maven deploy
        run: |
          if [ "${{ env.ACTIONS_STEP_DEBUG }}" == "true" ]; then
            mvn --batch-mode --activate-profiles deploy --settings $GITHUB_WORKSPACE/settings.xml -Pcoverage clean deploy -X -Dgpg.skip
          else
            mvn --batch-mode --activate-profiles deploy --settings $GITHUB_WORKSPACE/settings.xml -Pcoverage clean deploy -Dgpg.skip
          fi
        env:
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          # We removed GPG secrets here because we are skipping GPG signing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  get-tag-of-current-sha:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-retriever.outputs.tag }}
    steps:
      - name: Clone repo with complete history and tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Store tag of SHA if present
        id: tag-retriever
        run: |
          echo "tag=$(git describe --exact-match ${{ github.sha }})" >> "$GITHUB_OUTPUT" || echo "tag="

  trigger-github-release:
    needs: get-tag-of-current-sha
    name: Trigger GitHub release workflow
    if: needs.get-tag-of-current-sha.outputs.tag != ''
    uses: ./.github/workflows/release-on-github.yml
